import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Hero from "@/app/components/Hero";
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='flex items-center justify-center flex-col'>
        <Hero/>
        {children}
        </div>
        </body>
    </html>
  )
}
